###
GET http://localhost:3000/

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "secure123"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "first_name": "Alice",
  "last_name": "Mwangi",
  "email": "alice@example.com",
  "phone_number": "0712345678",
  "password": "secure123",
  "user_type": "user"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer <admin_token>

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "first_name": "admin",
  "last_name": "admin",
  "email": "admin@example.com",
  "phone_number": "0712345678",
  "password": "adminpass",
  "user_type": "admin"
}

### Get all users
GET http://localhost:3000/api/vehicles



### 
GET http://localhost:3000/api/users/4

### Create a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "first_name": "admin",
  "last_name": "admin",
  "email": "admin@example.com",
  "phone_number": "0712345678",
  "password": "adminpass",
  "user_type": "admin"
}

### Update user
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "tonny@example.com",
  "phone_number": "0723356478"
}

### Delete user
DELETE http://localhost:3000/api/users/1
